const flowCatalog = [
  ["safety-exterior-inspection", "Safety Exterior Inspection", "normal"],
  ["preliminary-cockpit-preparation", "Preliminary Cockpit Preparation", "normal"],
  ["cockpit-door-locking", "Cockpit Door Locking", "normal"],
  ["cockpit-preparation", "Cockpit Preparation", "normal"],
  ["before-pushback-start", "Before Pushback or Start", "normal"],
  ["pushback-start", "Pushback / Start", "normal"],
  ["engine-start", "Engine Start", "normal"],
  ["after-start-all-engine", "After Start - All Engine Taxi", "normal"],
  ["after-start-one-engine", "After Start - One Engine Taxi", "normal"],
  ["all-engine-taxi-departure", "All Engine Taxi at Departure", "normal"],
  ["one-engine-taxi-departure", "One Engine Taxi at Departure", "normal"],
  ["departure-change", "Departure Change", "normal"],
  ["before-takeoff", "Before Takeoff", "normal"],
  ["takeoff", "Takeoff", "normal"],
  ["after-takeoff", "After Takeoff", "normal"],
  ["climb", "Climb", "normal"],
  ["cruise", "Cruise", "normal"],
  ["descent-preparation", "Descent Preparation", "normal"],
  ["descent", "Descent", "normal"],
  ["approach", "Approach", "normal"],
  ["manual-landing", "Manual Landing", "normal"],
  ["automatic-landing", "Automatic Landing", "normal"],
  ["go-around", "Go Around", "normal"],
  ["after-landing", "After Landing", "normal"],
  ["one-engine-taxi-arrival", "One Engine Taxi at Arrival", "normal"],
  ["parking", "Parking", "normal"],
  ["crew-change-handover", "Crew Change / Handover", "normal"],
  ["securing-aircraft", "Securing the Aircraft", "normal"],
  ["memory-items", "Memory Items", "abnormal"],
  ["abnormal-procedures", "Abnormal Procedures", "abnormal"],
  ["emergency-procedures", "Emergency Procedures", "abnormal"],
];

const implementedFlows = {
  "after-landing": {
    id: "after-landing",
    name: "After Landing",
    trigger: "When vacating the runway",
    initialPanel: "glareshield",
    steps: [
      {
        role: "PF",
        panel: "pedestal",
        controlId: "speed-brake",
        action: "GND SPLRS",
        state: "DISARM",
      },
      {
        role: "PF",
        panel: "overhead",
        controlId: "strobe",
        action: "STROBE",
        state: "OFF",
      },
      {
        role: "PF",
        panel: "overhead",
        controlId: "landing-light-left",
        action: "LEFT LAND LIGHT",
        state: "OFF",
      },
      {
        role: "PF",
        panel: "overhead",
        controlId: "landing-light-right",
        action: "RIGHT LAND LIGHT",
        state: "OFF",
      },
      {
        role: "PF",
        panel: "overhead",
        controlId: "nose-light",
        action: "NOSE LIGHT",
        state: "TAXI",
      },
      {
        role: "PM",
        panel: "pedestal",
        controlId: "weather-radar",
        action: "WX RADAR / PREDICTIVE WINDSHEAR",
        state: "OFF",
      },
      {
        role: "PM",
        panel: "pedestal",
        controlId: "engine-mode",
        action: "ENG MODE SELECTOR",
        state: "NORM",
      },
      {
        role: "PM",
        panel: "pedestal",
        controlId: "flaps",
        action: "FLAPS",
        state: "RETRACT",
      },
      {
        role: "PM",
        panel: "pedestal",
        controlId: "xpndr-mode",
        action: "TCAS",
        state: "STBY / XPNDR",
      },
      {
        role: "PM",
        panel: "overhead",
        controlId: "wing-anti-ice",
        action: "ANTI-ICE",
        state: "AS RQRD",
      },
      {
        role: "PM",
        panel: "overhead",
        controlId: "pack-2",
        action: "PACK 2",
        state: "AS RQRD",
      },
      {
        role: "PM",
        panel: "overhead",
        controlId: "gpws-ldg-flap-3",
        action: "GPWS LDG FLAP 3",
        state: "OFF",
      },
      {
        role: "PM",
        panel: "overhead",
        controlId: "apu-master",
        action: "APU MASTER",
        state: "ON WHEN APPROPRIATE",
      },
      {
        role: "PM",
        panel: "overhead",
        controlId: "apu-start",
        action: "APU START",
        state: "START",
      },
      {
        role: "PM",
        panel: "glareshield",
        controlId: "fcu-appr",
        action: "FCU APPR PB",
        state: "DESELECT",
      },
      {
        role: "PM",
        panel: "glareshield",
        controlIdBySeat: {
          CM1: "capt-terrain",
          CM2: "fo-terrain",
        },
        action: "TERR ON ND",
        state: "OFF",
      },
      {
        role: "PM",
        panel: "pedestal",
        controlId: "ecam-lower-display-controls",
        action: "BRAKE TEMP",
        state: "MONITOR",
      },
      {
        role: "PM",
        panel: "glareshield",
        controlId: "brake-fan",
        action: "BRAKE FAN",
        state: "AS RQRD",
      },
    ],
  },
};
